hh-mitosig_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from . import views


app_name = 'hhmitosig_app'
urlpatterns = [
    path('', views.search, name='index'),
    path('search', views.search, name='search'),
    path('guide', views.guide, name='guide'),
    path('guidefirstInput', views.guideFirstInput, name='guideFirstInput'),
    path('guidesecondInput', views.guideSecondInput, name='guideSecondInput'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('tests', views.tests, name='tests'),
    path('running', views.running, name='running'),
    path('queued', views.queued, name='queueud'),
    path('file_not_found', views.file_not_found, name='file_not_found'),
    path('output_not_found', views.output_not_found, name='output_not_found')

#    path('', views.IndexView.as_view(), name='index'),
#    path('search', views.SearchView.as_view(), name='search'),
#    path('guide', views.GuideView.as_view(), name='guide'),
#    path('about', views.AboutView.as_view(), name='about'),
#    path('contact', views.ContactView.as_view(), name='contact'),
#    path('tests', views.TestsView.as_view(), name='tests'),
#    path('running', views.RunningView.as_view(), name='running'),
#    path('queued', views.QueuedView.as_view(), name='queueud'),
#    path('file_not_found', views.NotFoundView.as_view(), name='file_not_found'),
#    path('output_not_found', views.NotFoundView.as_view(), name='output_not_found')
]

handler404 = 'custom_404'

hh-mitosig_site/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from hhmitosig_site import settings

admin.autodiscover()

urlpatterns = [
    url(r'^', include('hhmitosig_app.urls', namespace="hhmitosig_app")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hh-mitosig_app/models.py
from django.db import models

# Create your models here.

hh-mitosig_app/forms.py
from django import forms
from django.db import models
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

# Custom validators
def custom_validate_email(email):
    """Function for additional e-mail validation"""
    #if not email.endswith('biochem.mpg.de'):
        #raise ValidationError('Only internal MPIB e-mails are allowed')

def custom_validator_job_name(job_name):
    """Function for additional job name validation"""
    if '"' in job_name:
        raise ValidationError('Double quotes are not allowed in job names')

def custom_validate_file(file_):
    """Function for additional uploaded file validation"""
    if file_.size > 1 * 1024 * 1024:
        raise ValidationError('The uploaded file is too large')


class FirstForm(forms.Form):
    form_type = forms.CharField(initial = 'first_form')
    input_text1 = forms.CharField(widget = forms.Textarea)
    user_email = forms.EmailField(validators = [validate_email,\
    custom_validate_email], required = False)
    ##
    job_name = forms.CharField(max_length = 50, required = False)

class SecondForm(forms.Form):
    form_type = forms.CharField(initial = 'second_form')
    input_text2 = forms.CharField(widget = forms.Textarea)
    second_form_file = forms.FileField(validators = [custom_validate_file], required = False) #By default, required = True
    user_email = forms.EmailField(validators = [validate_email,\
    custom_validate_email], required = False)
    ##
    job_name = forms.CharField(max_length = 50, required = False)

hh-mitosig_app/views.py
# Import
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
import re, os, pickle, datetime
from multiprocessing import Process
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
from django.contrib.sessions.models import Session
from django.http import HttpResponse, StreamingHttpResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.utils.safestring import mark_safe
from wsgiref.util import FileWrapper
from hhmitosig_app.forms import FirstForm, SecondForm
from hhmitosig_site.custom_methods import get_number_of_tasks, queue_the_task,\
generate_tag, ask_status, clear_record, start_session, get_session_dict,\
end_session, schedule_end_session
##
from hhmitosig_site.config import MAX_TASKS_QUEUED, SOME_PARAMETER
from hhmitosig_site.settings import BASE_DIR

TOOL_NAME = '<span class="tool-name">HH-MitoSig</span>'


# Create your views here.

#@csrf_exempt
#def index(request):
#    return redirect('search')

@csrf_exempt
def search(request):

    # Process an AJAX request (e.g., if checking of input is finished)
    if request.is_ajax():

        # Get the session key from the request
        # As the session key is stored at the client side, it needs a validity (injection safety) check before it can be used to fetch data from MySQL
        session_key = request.POST.get('session_key', '')
        session = None
        if re.search(r'^[0-9a-f]+$', session_key):
            session = get_session_dict(session_key)
        if not session:
            return HttpResponse('Connection timeout')

        # Get the job tag
        tag = session.get('tag', None)

        # Make a request to MySQL to check if the checking is finished
        status = ask_status(tag)
        if status == None:
            return HttpResponse('.RUNNING') #The checking is still running
        elif status == '': #The checking was successful

            # Get the user-defined parameters
            user_email = session.get('user_email', None)
            is_email = int(bool(user_email)) #0 if the user does not provide e-mail, 1 - otherwise
            if session.get('sent', None):
                clear_record(tag, 'prioritized')
                return HttpResponse('.SUCCESS {} {}'.format(tag, is_email))
            submit_time = session.get('submit_time', None)
            job_name = session.get('job_name', None)

            # Pickle the paraameters and register them with the main worker
            args = pickle.dumps( user_email, job_name, submit_time, tag)
            queue_the_task('heavy', args, tag)

            # Clean up
            end_session(session_key)
            clear_record(tag, 'prioritized')

            # Report success to the client and send relevant parameters to restore the state of the webpage and generate correct messages for the user
            return HttpResponse('.SUCCESS {} {}'.format(tag, is_email))

        else: #The checking completed with an error

            # Clean up
            end_session(session_key)
            clear_record(tag, 'prioritized')

            # Report the error to the client
            return HttpResponse(status)

    # Generating empty forms (in their default state)
    first_form = FirstForm()
    second_form = SecondForm()

    # Process GET request
    # This is usually the initial request to the server, so the default clean page is returned
    if not request.POST:
        dict_ = {'tool': mark_safe(TOOL_NAME),
                 'first_form': first_form,
                 'second_form': second_form}
        return render(request, 'hhmitosig_app/index.html', dict_)

    # Below is the processing of non-GET and non-AJAX requests, which should thus be POST
    # Such a request comes usually when the user clicks the submit button

    # Getting the working mode based on which exactly form was submitted
    first_form = FirstForm()
    second_form = SecondForm()
    mode = request.POST['form_type'].split('_')[0].upper()+'_MODE'
    input_file = None
    text_input1 = False
    text_input2 = False
    form_error = ''       # Establish the varibale for the error status

    # Check for server overload
    if get_number_of_tasks('heavy') >= MAX_TASKS_QUEUED:
        message = 'The server is overloaded now. Please try again later'
        messages.info(request, message)
        dict_ = {'tool': mark_safe(TOOL_NAME),
                 'mode': mode,
                 'first_form': first_form,
                 'second_form': second_form}
        return render(request, 'hhmitosig_app/index.html', dict_)


    # Process submission of main forms
    if mode == 'FIRST_MODE':
        first_form = FirstForm(data = request.POST, files = request.FILES)
        if first_form.is_valid(): #Check if the form passed the field validators
            input_fasta_text = first_form.cleaned_data['input_text1'] or ''
            if input_fasta_text:
                text_input1 = True
                input_file = ContentFile(input_fasta_text.encode()) #Save the content from the input text field as a virtual file
            user_email = first_form.cleaned_data['user_email'] or ''
            job_name = first_form.cleaned_data['job_name'] or ''
        else:
            for key in first_form.errors:
                form_error = '{} {}\n'.format(key, first_form.errors[key])
    elif mode == 'SECOND_MODE':
        second_form = SecondForm(data = request.POST, files = request.FILES)
        if second_form.is_valid():
            input_fasta_text = second_form.cleaned_data['input_text2'] or ''
            if input_fasta_text:
                text_input2 = True
                input_file = ContentFile(input_fasta_text.encode()) #Save the content from the input text field as a virtual file
            if 'second_form_file' in request.FILES:
                if text_input2:
                    form_error =\
                    'Select ONLY one input method: either text field or file'
                    ##
                input_file = request.FILES['second_form_file']
            user_email = second_form.cleaned_data['user_email'] or ''
            job_name = second_form.cleaned_data['job_name'] or ''
        else:
            for key in second_form.errors:
                form_error = '{} {}\n'.format(key, second_form.errors[key])

    # Make error meassages from the field validators tidier
    if form_error:
        form_error = re.sub(r'<.*?>', '', form_error)
        form_error = form_error.replace('input_text1', 'The input text:')
        form_error = form_error.replace('input_text2', 'The input text:')
        form_error = form_error.replace('second_form_file', 'The input file:')
        form_error = form_error.replace('user_email', 'E-mail:')
        messages.info(request, form_error)
        dict_ = {'tool': mark_safe(TOOL_NAME),
                 'mode': mode,
                 'first_form': first_form,
                 'second_form': second_form}
        return render(request, 'hhmitosig_app/index.html', dict_)

    try:

        # Generate auxiliary session information
        submit_time  = str(datetime.datetime.utcnow())[: -7] + ' UTC'
        tag = generate_tag(user_email)

        # Pickle the parameters for the cheking and register them with the checking worker
        args = pickle.dumps(mode, input_fasta_text, input_file, tag)
        queue_the_task('prioritized', args, tag)

        # Generate new session and fill it with relevant parameters
        session = {}
        session['mode'] = mode
        session['user_email'] = user_email
        session['job_name'] = job_name
        session['tag'] = tag
        session['submit_time'] = submit_time
        session['sent'] = False
        # Generate session key (the tag will be for now invidible for the user) and put the session in MySQL
        session_key = generate_tag('session_tag')
        start_session(session_key, pickle.dumps(session))

        # Start a process that will ensure the cleaning up of the database in case the client is disconnected (DoS security)
        Process(target = schedule_end_session, args = (session_key, 30)).start()

        # Return the 'Please wait...' page
        dict_ = {'tool': mark_safe(TOOL_NAME),
                 'mode': mode,
                 'session_key': session_key, #Presence of the session key will be the flag to the corresponding JavaScript at the client side
                 'first_form': first_form,
                 'second_form': second_form}
        return render(request, 'hhmitosig_app/index.html', dict_)

    except Exception as e: #Can occur if the MySQL server is down
        messages.info(request, str("Server internal error"))
        dict_ = {'tool': mark_safe(TOOL_NAME),
                 'mode': mode,
                 'first_form': first_form,
                 'second_form': second_form}
        return render(request, 'hhmitosig_app/index.html', dict_)

def guide(request):
    dict_ = {'inner_link': request.GET.get('l', '')}
    return render(request, 'hhmitosig_app/guide.html', dict_)

def guideFirstInput(request):
    dict_ = {'inner_link': request.GET.get('l', ''),
             'l':'first_mode_input'
             }
    return render(request, 'hhmitosig_app/guide.html' , dict_)

def guideSecondInput(request):
    dict_ = {'inner_link': request.GET.get('l', ''),
             'l':'second_mode_input'
             }
    return render(request, 'hhmitosig_app/guide.html', dict_)

def about(request):
    dict_ = {'tool': mark_safe(TOOL_NAME)}
    return render(request, 'hhmitosig_app/about.html', dict_)

def contact(request):
    return render(request, 'hhmitosig_app/contact.html')

# For requests to expired or never existent result pages
def output_not_found(request):
    dict_ = {'output': True}
    return render(request, 'hhmitosig_app/not_found.html', dict_)

# For request to absent downloadable files

hh-mitosig_app/templates/hh-mitosig_app/about.html
{% extends "hhmitosig_app/base.html" %}
{% load staticfiles %}

{% block about %}<li class="active"><a href="{% url 'hhmitosig_app:about' %}">About</a></li>{% endblock %}

{% block content %}
<div class="row">

    <div class="col-xs-12" style="text-align: justify">

        <h2 class="text-section">1. Title</h2>
        <hr class='line'></hr>
        <br />

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h2 class="text-section">2. Title</h2>
        <hr class='line'></hr>
        <br />

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

    </div>
</div>

{% endblock %}

hh-mitosig_app/templates/hh-mitosig_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>HH-MitoSig</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'hhmitosig_app/css/style.min.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'hhmitosig_app/js/adjuster.min.js' %}"></script>
    {% block load_additional_scripts %}{% endblock %}
</head>

<body>
    <div class="container">
        <div id="header" class="row">
            <div style="font-size:36px;height:50px; font-weight:bold; font-family: 'Arial'; background-color: darkcyan">
              <svg height="40" width="1000">
                <text x="40vw" y="5vh" fill="white"> HH-MITOSIG </text>
              </svg>
            </div>
            <ul id="main_menu" class="nav nav-tabs">
                {% block index %}<li><a href="{% url 'hhmitosig_app:search' %}">Search</a></li>{% endblock %}
                {% block guide %}<li><a href="{% url 'hhmitosig_app:guide' %}">Guide</a></li>{% endblock %}
                {% block about %}<li><a href="{% url 'hhmitosig_app:about' %}">About</a></li>{% endblock %}
                {% block contact %}<li><a href="{% url 'hhmitosig_app:contact' %}">Contact</a></li>{% endblock %}
            </ul>
        </div>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>

</html>

hh-mitosig_app/templates/hh-mitosig_app/contact.html
{% extends "hhmitosig_app/base.html" %}
{% load staticfiles %}

{% block contact %}<li class="active"><a href="{% url 'hhmitosig_app:contact' %}">Contact</a></li>{% endblock %}

{% block content %}
<div class = "textContainer">
    In case of problems please contact <a href="mailto:susun@biochem.mpg.de">Su Sun</a>.
</div>
<div class= "formContainer">
	<div class="center-wrapper">
		<a href="http://www.mpg.de" target="_blank"><img src="{% static 'hhmitosig_app/img/mpglogo.png' %}" style="width:22.5%; border:0;" alt="MPG emblem" /></a>
		<br></br>
		<a href="http://www.biochem.mpg.de/en" target="_blank"><img src="{% static 'hhmitosig_app/img/logo-mpi-biochem.png' %}" style="width:35%; border:0;" alt="MPI Biochem"></a>
	</div>
</div>
{% endblock %}

hh-mitosig_app/templates/hh-mitosig_app/guide.html
{% extends "hhmitosig_app/base.html" %}
{% load staticfiles %}

{% block load_additional_scripts %}
<script type="text/javascript" src="{% static 'hhmitosig_app/js/guide.min.js' %}"></script>


{% endblock %}

{% block guide %}<li class="active"><a href="{% url 'hhmitosig_app:guide' %}">Guide</a></li>{% endblock %}

{% block content %}
<div class="row">
    <div class="sidebar-container">
        <ul id="guide_nav_menu" class="nav">
            <li class="dropdown">
                <button id="btn-menu" type="button" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-menu-hamburger" style="font-size: 2em"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <div id="guide_nav_menu_inner_div" class="navbar sidebar-left"></div>
                    </li>
                </ul>
            </li>
        </ul>
        <div id="guide_nav_normal" class="navbar sidebar-left">
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a class="sidebar-link guide-pseudo-button" href="#general_info">1. General Information</a></li>
                <li><a class="sidebar-link guide-pseudo-button" href="#first_mode_input">2. First Mode Input</a></li>
                <li><a class="sidebar-link guide-pseudo-button" href="#first_mode_output">3. First Mode Output</a></li>
                <li><a class="sidebar-link guide-pseudo-button" href="#second_mode_input">4. Second Mode Input</a></li>
                <li><a class="sidebar-link guide-pseudo-button" href="#second_mode_output">5. Second Mode Output</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-lg-9 col-md-9 col-md-offset-3 col-sm-11 col-sm-offset-1 col-xs-11 col-xs-offset-1" style="text-align: justify">

        <h2 id="general_info" class="text-section">1. General Information</h2>
        <hr class="line"></hr>

        <h3 class="text-sub-section">Terms of use</h3>
        <p>This tool is free for both academic and non-academic use.
        No registration is required to access the full functionality of the server.
        However, if you need to process larger protein sets, please <a href="{% url 'hhmitosig_app:contact' %}">contact</a> the authors to get a standalone version for LINUX.
        </p>
        <p>Please note that results are stored on the server only for 7 days.
        </p>

        <h3 class="text-sub-section">Requirements</h3>
        <p>The website design is kept simple and light-weight.
        Cookies as well as additional plugins are not required.
        All modern browsers (starting from IE9) are supported.
        The website is fully mobile-friendly.
        </p>
        <p>This website uses Javascript, both for submit and result pages.
        Please make sure that Javascript is enabled whenever you use the server or view results.
        </p>

        <h3 class="text-sub-section">Security and privacy</h3>
        <p>The web server does not collect any information about the users.
        Submission of the data can be done completely anonymously; however, users have the option to provide an e-mail address for a notification on job completion.
        Each accepted job gets a unique randomly generated identifier (a 40-character long hexadecimal string), which is required to access the results.
        Please share this identifier only with persons, who are authorized to view the results.
        The results will be permanently deleted from the server on the 8th day upon the job completion.
        </p>

        <h3 class="text-sub-section">More information</h3>
        <p>This guide addresses mainly the technical aspects of using the server.
        For information about the scope of use and internal workflow, please visit the <a href="{% url 'hhmitosig_app:about' %}">About</a> page.
        </p>

        <h2 id="first_mode_input" class="text-section">2. First Mode Input</h2>
        <hr class="line"></hr>

        <p>The link from the 'More help' button on the first form scrolls to this section.
        </p>

        <h3 class="text-sub-section">Input file</h3>
        <p>Input file description. You can also scroll to the <a class="guide-pseudo-button" href="#first_variable">variable description</a>.
        </p>
        <ul style="margin-left: 2em">
            <li>Point A</li>
            <li>Point B</li>
            <li>Point C</li>
            <li>Point D</li>
        </ul>
        <div class="sample-download" style="float: left"><a href="{% static 'hhmitosig_app/downloads/file.fasta' %}" download target="_blank">Sample</a></div>
        <div style="clear:both"></div>
        <div style="height: 0.5em"></div>

        <h3 id="first_variable" class="text-sub-section">Variable</h3>
        <p>Variable description. The link from the input file description scrolls here.
        </p>

        <h2 id="first_mode_output" class="text-section">3. First Mode Output</h2>
        <hr class="line"></hr>

        <br />
        <div class="sample-output"><a href="../downloads/test_results_first/results.html" target="_blank">Output sample</a></div>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Submission information</h3>
        <p>The information about the job submission (including all the input parameters) is provided at the bottom of the output page.
        </p>

        <h2 id="second_mode_input" class="text-section">4. Second Mode Input</h2>
        <hr class="line"></hr>

        <p>The link from the 'More help' button on the second form scrolls to this section.
        </p>

        <h3 class="text-sub-section">Input file</h3>
        <p>Input file description. You can also scroll to the <a class="guide-pseudo-button" href="#second_variable">variable description</a>.
        </p>
        <ul style="margin-left: 2em">
            <li>Point A</li>
            <li>Point B</li>
            <li>Point C</li>
            <li>Point D</li>
        </ul>
        <div class="sample-download" style="float: left"><a href="{% static 'hhmitosig_app/downloads/file.fasta' %}" download target="_blank">Sample</a></div>
        <div style="clear:both"></div>
        <div style="height: 0.5em"></div>

        <h3 id="second_variable" class="text-sub-section">Variable</h3>
        <p>Variable description. The link from the input file description scrolls here.
        </p>

        <h3 class="text-sub-section">Other parameters</h3>
        <p>Description
        </p>

        <h2 id="second_mode_output" class="text-section">5. Second Mode Output</h2>
        <hr class="line"></hr>

        <br />
        <div class="sample-output"><a href="../downloads/test_results_second/results.html" target="_blank">Output sample</a></div>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

        <h3 class="text-sub-section">Subtitle</h3>
        <p>Content
        </p>

    </div>

</div>
<div style="height: 99vh"></div>

<!--Hidden sesion info-->
<div class="session-info">
    <a id="inner_router" class="guide-pseudo-button" href="#{{inner_link}}"></a>
</div>

<script>

    if('{{ l }}' == 'first_mode_input' || '{{ l }}' == 'second_mode_input'){
      location.hash = '#{{ l }}';
      window.addEventListener("hashchange", function() { scrollBy(0, -100) })
    }
</script>
{% endblock %}

hh-mitosig_app/templates/hh-mitosig_app/not_found.html
{% extends "hhmitosig_app/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">

    <div style="text-align: center">
        <h2 class="text-section">Requested File Not Found</h2>
    </div>
    {% if output %}
        <p class="main-descr"><br />
        It seems like you are trying to access a results page that does not exist.
        <br /><br />
        This may be happening for two following reasons:
        <ul style="padding-left: 2em">
            <li>The provided identifier is not correct.
            Please make sure that you copy and pase the URL correctly.
            The identifier is always a 40-character long hexadecimal string.</li>
            <li>The results are expired.
            Note that all results are stored only for 7 days and are permanently deleted afterwards.</li>
        </ul>
        </p>
    {% endif %}

</div>
{% endblock %}

hh-mitosig_app/templates/hh-mitosig_app/queued.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>HH-MitoSig results</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device-width, initial-scale=1.0" />
    <meta http-equiv="refresh" content="30" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'hhmitosig_app/js/spin.min.js' %}"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'hhmitosig_app/css/style.css' %}" />
    <script>
        $(document).ready(function () {
            var opts={position: "relative", scale: "0.75"};
            var spinner = new Spinner(opts).spin();
            $("#spinner_anchor").append(spinner.el);
        });
    </script>
</head>

<body>
    <div class="container">
        <div id="header" class="row">
            <div id="logo_wrapper"><img id="logo" src="{% static 'hhmitosig_app/img/logo.svg' %}" alt="Logo" /></div>
        </div>
        <div class="row" style="margin-bottom: 4em"></div>
        <div class="row">
            <div>
                <div style="float: left"><p>Your task is waiting in the queue...</p></div>
                <div id="spinner_anchor" class="spinner-in-text"></div>
            </div>
            <div style="clear: both"></div>
            <p>To see if the calculations are finished, you can <a href="">refresh</a> the page.</p>
            <p>The page will be refreshed automatically every 30 seconds.</p>
            <p>You can also bookmark this page and visit it later.</p>
            <p>In case you have provided your e-mail address, you will be notified as soon as the calculations are complete.</p>
            <p>Please note that the results will be stored only for 7 days.</p>
        </div>
    </div>
</body>

</html>

hh-mitosig_app/templates/hh-mitosig_app/running.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>HH-MitoSig results</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device-width, initial-scale=1.0" />
    <meta http-equiv="refresh" content="30" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'hhmitosig_app/js/spin.min.js' %}"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'hhmitosig_app/css/style.css' %}" />
    <script>
        $(document).ready(function () {
            var opts={position: "relative", scale: "0.75"};
            var spinner = new Spinner(opts).spin();
            $("#spinner_anchor").append(spinner.el);
        });
    </script>
</head>

<body>
    <div class="container">
        <div id="header" class="row">
            <div id="logo_wrapper"><img id="logo" src="{% static 'hhmitosig_app/img/logo.svg' %}" alt="Logo" /></div>
        </div>
        <div class="row" style="margin-bottom: 4em"></div>
        <div class="row">
            <div>
                <div style="float: left"><p>Your task is running right now...</p></div>
                <div id="spinner_anchor" class="spinner-in-text"></div>
            </div>
            <div style="clear: both"></div>
            <p>To see if the calculations are finished, you can <a href="">refresh</a> the page.</p>
            <p>The page will be refreshed automatically every 30 seconds.</p>
            <p>You can also bookmark this page and visit it later.</p>
            <p>The calculation time depends on many parameters, first of all on sequence length.
            However, it is typically from X to Y minutes per query submitted.
            If you cannot see the results for too long, make sure that page refreshments are not suppressed by your browser.
            If you cannot see the results after more than 12 hours, please <a href="{% url 'hhmitosig_app:contact' %}" target="_blank">contact</a> the server administration.</p>
            <p>In case you have provided your e-mail address, you will be notified as soon as the calculations are complete.</p>
            <p>Please note that the results will be stored only for 7 days.</p>
        </div>
    </div>
</body>

</html>